# Numpy

In [1]:
import numpy as np

## Creating Arrays

In [7]:
# One dimension, Rank 1 (Vector)
data = [1, 2, 3.5, 4, 0]
vector = np.array(data)
vector

array([1. , 2. , 3.5, 4. , 0. ])

In [8]:
# Two dimension,Rank 2 (Matrix)
matrix = [data,data]
matrix

[[1, 2, 3.5, 4, 0], [1, 2, 3.5, 4, 0]]

In [14]:
# Three dimension,Rank 3 (Tensor)
tensor = [[data,data]]
tensor

[[[1, 2, 3.5, 4, 0], [1, 2, 3.5, 4, 0]]]

In [20]:
# Shape
shape_vector = np.shape(vector)  # (5,)
shape_matrix = np.shape(matrix)  # (2, 5)
shape_tensor = np.shape(tensor)  # (1, 2, 5)

In [24]:
# Dimension 
dim_vector = np.ndim(vector)  # 1
dim_matrix = np.ndim(matrix)  # 2
dim_tensor = np.ndim(tensor)  # 3

Creating an array with zeros

In [23]:
# Zeros array 
zeros_arr = np.zeros(5)
zeros_arr2 = np.zeros((5,2))
zeros_arr2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
# Ones array 
ones_arr = np.ones(5)
ones_arr2 = np.ones((5,2))
ones_arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
# Arange array - np.arange(start, stop, step, dtype=None)
n_arange = np.arange(1, 10, 2)
n_arange = np.arange(1,11, 2.5999, dtype=float)
n_arange

array([1.    , 3.5999, 6.1998, 8.7997])

In [160]:
# Identity
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Operations between Arrays and Scalars

In [26]:
arr = np.array([1, 2 , 3, 4, 5])

Sum 

In [28]:
Sum = arr + arr
Sum

array([ 2,  4,  6,  8, 10])

Difference

In [30]:
dif = arr - arr
dif

array([0, 0, 0, 0, 0])

Division

In [31]:
div = 1/arr_a
div

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

Multiplication

In [33]:
mult = arr * arr
mult

array([ 1,  4,  9, 16, 25])

## Index and Slicing

In [34]:
# Array of one Dimensionn from 0 to 9
arr_a = np.arange(0, 10)
# Replace the number with index 0 with 99
arr_a[0] = 99
#Replace the numbers from the index 5 to the end with 9999
arr_a[5::] = 9999
arr_a

array([  99,    1,    2,    3,    4, 9999, 9999, 9999, 9999, 9999])

In [35]:
# Array of two Dimensionn of zeros
arr_b = np.ones((5,5))
#Replace the numbers from the index 2,2 with 0
arr_b[2][2] = 0
arr_b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# Array of three Dimensions of ones
arr_c = np.ones((5,2,2))
#Replace the numbers from the index 4,1,1 with 99
arr_c[4][1][1] = 99
arr_c

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1., 99.]]])

## Boolean Indexing 

In [51]:
# Array 
arr_d = np.arange(1, 100, 5)
# Replacing all numbers above 50 with 99
arr_d[arr_d > 50] = 99
arr_d

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99])

## Reshaping

In [53]:
arr_e = np.arange(1,41).reshape((4,10))
arr_e

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

## Mathematical and Statistical Methods

In [82]:
# Creating an array with 10 random decimal numbers
arr_e = np.random.randn(5,2,1).reshape(5,2)
# Creating an array with 10 random integer numbers
arr_f = np.random.randint(1,10,10).reshape(5,2)
arr_f

array([[2, 4],
       [3, 9],
       [5, 7],
       [9, 4],
       [2, 8]])

In [89]:
# Mean of all the array
mean = np.mean(arr_f)
# Mean of the colummns - axis 0 
mean_axis0 = np.mean(arr_f, axis=0)
mean_axis0

array([4.2, 6.4])

In [86]:
# Sum all the values in the array
Sum = np.sum(arr_f)

In [93]:
# Max and Min value
Max = np.max(arr_f)
Min = np.min(arr_f)

In [99]:
# Standard deviation and variance
Std = np.std(arr_f)
Var = np.var(arr_f)

In [109]:
# Sort an Array 
# Create a random array using randint
random_arr = np.random.randint(1,10,10)
# Sort using np.sort(random_arr)
sort_arr = np.sort(random_arr)
sort_arr

array([1, 1, 2, 3, 3, 4, 8, 8, 9, 9])

## Unique

In [112]:
# Unique fuction returns a sorted unique values in the array
names = np.array(['Bob', 'Alice', 'Alice', 'Bob', 'John', 'John', 'John', 'Bob'])
unique_name = np.unique(names)
unique_name

array(['Alice', 'Bob', 'John'], dtype='<U5')

In [118]:
# Array with numbers
arr_g = [7, 9, 4, 9, 6, 3, 1, 4, 4, 6]
arr_g

[7, 9, 4, 9, 6, 3, 1, 4, 4, 6]

In [120]:
unique_num = np.unique(arr_g)
unique_num

array([1, 3, 4, 6, 7, 9])

## Linear Algerbra

In [130]:
# Dot multiplication (Scalar product)
x = np.random.randn(6).reshape(3, 2)
y = np.random.randn(4).reshape(2, 2)
scalar = x.dot(y)
scalar

array([[ 0.10472622, -1.34583713],
       [-0.89641146,  0.62763709],
       [-0.23821771, -0.0022925 ]])

In [145]:
# Inverse matrix
# Import inv from numpy
from numpy.linalg import inv
x = np.array([[2, 3, 4],[9, 8, 8],[2, 3, 5]])
x_inv = inv(x)
x_inv

array([[-1.45454545,  0.27272727,  0.72727273],
       [ 2.63636364, -0.18181818, -1.81818182],
       [-1.        ,  0.        ,  1.        ]])

In [147]:
# Trace
traceX = np.trace(x)
traceX

15

In [152]:
# Determinant
detX = np.linalg.det(x)
detX

-11.000000000000002

In [159]:
# Solve Ax = b, where A is asquare matrix
A = np.arange(4).reshape(2,2)
b = np.array([100,200])
x = np.linalg.solve(A, b)
x

array([-50., 100.])